on:
  push:
    branches: [test_deploy]

env:
  BUILD_FILE: demo-0.0.1-SNAPSHOT.jar
  DEPLOYMENT_FOLDER: /home/shajahan/simplogics/presentation/new_folder/deployment

jobs:
  build:
    runs-on: runner_1
    name: build
    steps:
    - uses: actions/checkout@v3
    - run: mvn clean package
  deploy:
    runs-on: runner_1
    name: deploy
    needs: [build]
    steps:
    - run: cp target/$BUILD_FILE $DEPLOYMENT_FOLDER
    - run: sudo systemctl start cicdseminar.service